### ISSUE TITLE
clarification for installation needed

### ISSUE THREAD

**Issue by hippocritical** [abanchev/binance-proxy#9]
Hi, 

could you place a dummy setup including freqtrade on the repo?
Some things are not clear, having issues using your proxy.

Getting errors like that, despite copying it over.
It would be beneficial aswell if you didnt use the 8080 port since that is the default freqtrade port aswell.
Could you make the example with the container name instead of 127.0.0.1?

binance-proxy  | internal/modules/cjs/loader.js:328
binance-proxy  |       throw err;
binance-proxy  |       ^
binance-proxy  | 
binance-proxy  | Error: Cannot find module '/usr/src/app/src/index.js'. Please verify that the package.json has a valid "main" entry
binance-proxy  |     at tryPackage (internal/modules/cjs/loader.js:320:19)
binance-proxy  |     at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)
binance-proxy  |     at resolveMainPath (internal/modules/run_main.js:16:25)
binance-proxy  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:70:24)
binance-proxy  |     at internal/main/run_main_module.js:17:47 {
binance-proxy  |   code: 'MODULE_NOT_FOUND',
binance-proxy  |   path: '/usr/src/app/package.json',
binance-proxy  |   requestPath: '/usr/src/app'
binance-proxy  | }

Thx!

**Comment by fmhc** [comment]
looks like you have an outdated nodejs version. using port 8080 is totally fine if you wrap this in a docker container and then have an other port plugged into that. if you want to hard wire another port, change the 8080 in the server.js file
